trigger: none

pr:
- master

pool:
  vmImage: 'Ubuntu-latest'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

variables:
- group: ci-detective
- name: environment
  value: Sonar

steps:
- task: GoTool@0
  displayName: 'Use Go 1.15'
  inputs:
    version: 1.15

- script: |
    export GOPATH=$(go env GOPATH)
    PATH=$PATH:$GOPATH/bin
    curl -sL https://taskfile.dev/install.sh | sh -s -- -b $GOPATH/bin
    task setup
    export PROJECT_VERSION=$(task print-version)
    echo "##vso[task.setvariable variable=projectVersion]$PROJECT_VERSION"
  displayName: 'Install dependencies'

- bash: |
   export GOPATH=$(go env GOPATH)
   PATH=$PATH:$GOPATH/bin
   task ci
  displayName: 'Run CI script'

- task: PublishTestResults@2
  displayName: 'Publish unit test results'
  inputs:
    testResultsFiles: '$(junitXmlResultsFileName)'
    searchFolder: '$(testResultsDirPath)'
    testRunTitle: '$(prTestResultsTitle)'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(fullCoberturaResultsFilePath)'
    reportDirectory: '$(covResultsDirPath)'
  condition: succeededOrFailed()

- template: templates/yml/any/sonar/run-sonar-cloud-cli-analysis.yml@templates
  parameters:
    projectVersion: $(projectVersion)
